### PR TITLE
chore: add stride outpost script

### PR DESCRIPTION
**Pull request by GAtom22**

### CODE REVIEW

**Review by Vvaradinov — APPROVED** [review]
LGTM!

**Comment by MalteHerrmann** [comment]
@GAtom22 @Vvaradinov what do you guys want to do with this now that we've moved to the client side outpost implementation? 🤔

**Comment by Vvaradinov** [comment]
@MalteHerrmann we could safely remove this I think. Alternatively we can replace it with the Solidity Outpost and do some testing for it? It's really optional at this point

**Comment by MalteHerrmann** [comment]
Lets close this then, we can reopen should we ever need this again 👍

**Pull request closed without merging**
